#ifndef __config_h__
#define __config_h__

enum {
   EDITOR_CONFIG_COLOR_VARIANT_BASE,
   EDITOR_CONFIG_COLOR_VARIANT_OUTLINE,
   EDITOR_CONFIG_COLOR_VARIANT_TEXT,

   EDITOR_CONFIG_COLOR_VARIANT__NUM
};

enum {
   EDITOR_CONFIG_COLOR_STATE_IDLE,
   EDITOR_CONFIG_COLOR_STATE_OVER,
   EDITOR_CONFIG_COLOR_STATE_DOWN,
   EDITOR_CONFIG_COLOR_STATE_OVER_DOWN,
   EDITOR_CONFIG_COLOR_STATE_SELECTED,
   EDITOR_CONFIG_COLOR_STATE_SELECTED_OVER,
   EDITOR_CONFIG_COLOR_STATE_DISABLED,

   EDITOR_CONFIG_COLOR_STATE__NUM
};

typedef enum {
	POSITION_LEFT,
	POSITION_RIGHT,
	POSITION_TOP,
	POSITION_BOTTOM
} EDITOR_CONFIG_POSITION;


#endif
